### ISSUE TITLE
Threading issue with package descriptions

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#118]
Steps to reproduce:
1. open yumex-dnf
2. open a long list of packages, e.g. all packages marked as "Available" or "Installed" or "All"
3. select a package
4. make sure package description is visible
5. press the "down" arrow and keep it pressed for a long time, waiting to scroll through >100 packages
6. have a look at packages description

What happens:
Sometimes, within 5., yumex-dnf crashes. Have a look at [rhbz #1337218](https://bugzilla.redhat.com/show_bug.cgi?id=1337218) for a traceback.
Often, at 6., package description is cluttered, showing contents twice or repeated for a dozen times.

Another steps to reproduce:
1. open "Packages" view, mark all "Available" packages
2. do fast, repeated right-clicks (context menu click) on the package list

What happens:
Sometimes, description appears twice, including all the URLs. See also [rhbz #1337768](https://bugzilla.redhat.com/show_bug.cgi?id=1337768) for a traceback.

I think (though I am not 100% sure) that this is an issue caused by incorrect handling of threads. Is yumex-dnf multithreaded? If yes, can't it be single-threaded? The only blocking I/O except minor theming stuff is done by dnf-daemon. If all dbus calls were async, I'd see no reason to have multiple threads running. Am I wrong?

**Comment by timlau** [comment]
Yumex-dnf is not miltithreaded, this is caused by long running async dbus calles to dnf-daemon like loading all packages, the gui is not locked while adding packages to the view, so this can give these kind of issues

**Comment by timlau** [comment]
the problem is that every time a new package is selected a signal is send from the package view to the main application, that trigger an update on the package information view, there is fetching infomation from the dnf-daemon dbus backend.
When you hold down the key a lot of changes of the active package happends and we can get information and update, before the next change is happening,so we get some kind of race condition.
The easy solution is locking the gui while getting the information from the backend, it solves the tracebacks because the down arrow key is not work before the information is fetched an updated.
The problem with the solution is you get flickering in the gui and you can move faster down the list than you can get infomation from the backend.
The best solution would be not fetching information if changes happens to fast, the package need to selected for a periode of time before, the change signal is send. but it is more complex todo
