### ISSUE TITLE
No official repo for fedora 25

### ISSUE THREAD

**Issue by ahloiscreamo** [timlau/yumex-dnf#147]
i am using copr build, i hope official f25 repo will be update soon.Thanks!

**Comment by kn00tcn** [comment]
you mean f25 is on 4.3.2 & you want it to officially be updated?

**Comment by ahloiscreamo** [comment]
ah yes if that possible, btw i just upgrade to fedora 25 and yumex work fine except i got error about cannot reach copr yumex something on terminal.I will update again tonight (in my workplace now) thanks.

**Comment by kn00tcn** [comment]
copr is not official, make sure to look at the actual copr page & package list to see all the right numbers & files

on a related note, i was looking for compton, someone had it in copr but they forgot to make an item for f25, they only had f24, so one trick i did was manually editing the repo information file so that it says '/fedora-25-x86_64/' instead of '/fedora-$releasever&arch=$basearch/' which would return an error unless i was on f24

**Comment by ahloiscreamo** [comment]
Hi there.Thanks for the tip!.I managed to solve the issue by installing yumex-dnf-4.3.3-2.fc25.noarch and removing the copr build.(idk it is available in the fedora repo in the first place TT??!) thanks again and have a nice day

**Comment by genodeftest** [comment]
The copr hasn't been updated for Fedora 25, but you should just use the official Fedora 25 repositories. Both repos contain the latest version 4.3.3, so it doesn't make a difference anyway.
