### ISSUE TITLE
Preferences menu issue.

### ISSUE THREAD

**Issue by eddy02** [timlau/yumex-dnf#162]
Glad to just discover that this project is no longer abandoned.

When l click  on the preferences menu , yumex  always starts by fetching  the  repositories informations so  the transaction is slow.
Thanks.

**Comment by timlau** [comment]
I know it is because there have been some changes in dnfdaemon there is returning the number of packages in each repo also the disabled ones, when getting a list of avaliable repositories and it take a long time.
I have to work around it some how, maybe som lazy loading, so repositories is first fetched when the repo page is selected or something like that.

**Comment by timlau** [comment]
fixed
