### ISSUE TITLE
Failed builds on copr

### ISSUE THREAD

**Issue by SkeleySash** [timlau/yumex-dnf#179]
Your last build of yumex-dnf failed to build for all versions of Fedora. Maybe there's a way to get it to auto rebuild once new changes have been made to the git version. 

Also, would it be possible to port it to GTK 4 and use libawaita? Not sure what your plans are once Fedora moves to dnf5

**Comment by timlau** [comment]
Looks like it is the armfp build there not able so build, it is not importent so i removed it.
It don't want to make a build on each commit, want to make sure it is in a working state before making copr builds.

I might do a total rewrite using gtk4/libawaita and using the dnf5 dbus API, if I get the time in the future.

But the road forward for fedora will properly go into the silverblue direction, with an imutable base OS and flatpak for application, so a tool like yumex might not make much sense in that world.

**Comment by SkeleySash** [comment]
I understand. Thank you for letting me know. 

If that's the case, I may as well stick to Arch Linux or openSUSE Tumbleweed because I'm not really a big fan of flatpaks.

**Comment by Henkire** [comment]
Hey uh, I know this is quite random for me to say something once again, but lately I've been unhappy with how KDE is working for me. 

I do wish to use Fedora Workstation and I honestly love your application. I wish I knew how to code to help contribute because I would love to see it rebuilt using GTK4 and libadwaita. It would look so good. It would be a big undertaking, especially if you were to update the underlying code to use dnf5 once that's in use in Fedora 38 or 39. 

Advanced GUI package managers make me smile. idk about silverblue though. I know they want it to be the future, but I doubt it can replace regular Fedora anytime soon. Maybe in like 5 years or something.

**Comment by timlau** [comment]
@Henkire check out
https://github.com/timlau/yumex-ng

**Comment by Henkire** [comment]
Oh my god yes I'm loving this alreadyy
