### ISSUE TITLE
Use text color from current theme in package view

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#63]
Use the color from the current theme to show available packages in the package view

Relates to #42 & #49

**Comment by genodeftest** [comment]
There is just one single text color in Gtk.
For the PackageInfoView you could use a GtkSourceView with specific highlight syntax using a so-called "language spec". Those are tested and widely deployed, but don't automatically change with the theme. You could use indentation instead of manually filling with spaces.

For GtkTreeView there is no such solution.
